### ISSUE TITLE
Can't import secp256k1 with new version of secp256k1-py

### ISSUE THREAD

**Issue by mbroedel** [hyperledger/sawtooth-sdk-python#29]
When using [secp256k1-py](https://pypi.org/project/secp256k1/) on the newest version 0.14, importing secp256k1 errors out:

```
>>> from sawtooth_signing import secp256k1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/venv/lib/python3.8/site-packages/sawtooth_signing/__init__.py", line 19, in <module>
    from sawtooth_signing.secp256k1 import Secp256k1Context
  File "/opt/miniconda3/envs/venv/lib/python3.8/site-packages/sawtooth_signing/secp256k1.py", line 28, in <module>
    __CONTEXTBASE__ = secp256k1.Base(ctx=None, flags=secp256k1.ALL_FLAGS)
AttributeError: module 'secp256k1' has no attribute 'Base'
```

Looks like this is the first new version in five years, so it was bound to break something.

**Comment by ryanwwest** [comment]
I'm running into the same issue. However, I also get the issue trying older versions on pip.

**Comment by mbroedel** [comment]
Will there be a new pip version of the package as well? Installing via pip still doesn't work

**Comment by mbroedel** [comment]
Great, thank you!
